[project]
name = "afplotter"
version = "0.1.0"
description = "A standalone HEP plotting library"
authors = [
    {name = "Alexander Heidelbach", email = "alexander.heidelbach@kit.edu"},
    {name = "Frederik Schmitt", email = "frederik.schmitt@kit.edu"},
]
dependencies = [
    "matplotlib",
    "numpy",
    "polars",
    "cycler",
    "importlib_resources",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff==0.5.0", "mypy==1.10.1"]

[tool.ruff]
line-length = 120
lint.ignore = ["E402"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401", "F403", "E402"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"afplotter.experiments" = ["*.mplstyle"]

[tool.pytest.ini_options]
testpaths = ["tests"]
